<?php

/**
 * ProcessWire Social Login Process, displays Social Logins in Setup > Social Logins > 
 * 
 *
 * ProcessWire 2.2 
 * Copyright (C) 2012 by Oliver Wehn
 * Licensed under GNU/GPL v2
 * 
 * http://www.processwire.com
 * http://www.oliverwehn.com
 *
 */

class ProcessSocialLoginManager extends ProcessPageType {

    static public function getModuleInfo() {
        return array(
            'title' => 'Social Login Manager',
            'version' => 100,
            'summary' => 'Manage social login modules',
			'author' => 'Oliver Wehn',
			'singular' => true,			
            );
    }


	/**
	 * Populate the fields shown in the default language list output
	 *
	 */
	public function __construct() {
		parent::__construct();
		$this->pages = $this->fuel('pages');
		$this->set('showFields', array('title', 'users'));
	}
	
	/**
	 * Init it 
	 *
	 */
	public function init() {
	    
	}
	
	/**
	 * Render config form
	 */
	public function ___executeEdit() {
		if((is_numeric($this->input->get->id)) && ($module_page = $this->pages->get($this->input->get->id))) {
			$this->fuel->breadcrumbs->add(new Breadcrumb('../', $this->page->title));
			$this->page->title .= ": ".$module_page->title; 
			$form = $this->modules->get('InputfieldForm');
			$form->action = "../save/?id=".$this->input->get->id;
			$form->attr('method', 'post');
			// let login module add specific input fields to form
			$config = $this->modules->getModuleConfigData($module_page->process);
            $module = $this->modules->get($module_page->process);
			if($fields = $module->getModuleConfigInputfields($config)) {
				foreach($fields as $field) {
					if($field instanceof Inputfield) {
						$form->add($field);
					}
				}
			}
			// add submit button
			$field = $this->modules->get('InputfieldButton');
			$field->type = "submit";
			$field->name = "confirm";
			$field->value = $this->_("Save");
			$form->add($field);
			return $form->render();
		} else {
			$this->message($this->_("No login module to edit."));
			$this->session->redirect("../");
		}
	}
    
    public static function getRoleConfigField($user_roles) {
            // prepare roles
            $roles = Wire::getFuel('roles');
            if(!is_array($user_roles)) {
                $user_roles = explode("|", $user_roles);
            }
            $value = new PageArray();
            if(is_array($user_roles)) {
                foreach($user_roles as $role) {
                    $value->add($roles->get($role));
                }
            }
            // offer user roles to choose
            $roles_field = Wire::getFuel('fields')->get('roles');
            $field = $roles_field->getInputfield(Wire::getFuel('page'), $roles_field);
            $field->label = __("User roles", __FILE__);
            $field->description = __("Roles given to users created for this type of login by default", __FILE__);
            $field->value = $value;
            $field->name = 'user_roles';
            return $field;        
    } 
    

	/**
	 * Save config data
	 */
	public function ___executeSave() {
		if($this->input->get->id) {
			$config = array();
            
			if((!array_key_exists('user_roles', $config)) || (!is_array($config['user_roles']))) {
				$config['user_roles'] = "";
			} else {
			    $config['user_roles'] = implode("|", $config['user_roles']);
			}
			$match = array();
			foreach($this->input->post as $name => $value) {
				$config[$name] = $value;
			}
			$this->modules->saveModuleConfigData($this->pages->get($this->input->get->id)->process, $config);
			$this->message($this->_("Config data successfully saved"));
			$this->session->redirect("../");
		} else {
			$this->message($this->_("No config data was saved."));
			$this->session->redirect("../");
		}
	}	

	/**
	 * Render list of social login modules
	 * 
	 */
	protected function renderList() {
		$out = '';
		$table = $this->modules->get("MarkupAdminDataTable"); 
		$table->setEncodeEntities(false); 
		$fieldNames = $this->showFields; 
		$fieldLabels = $fieldNames; 
		foreach($fieldLabels as $key => $name) {
			if($name == 'name') {
				$fieldLabels[$key] = $this->_('Name'); // Label for 'name' field
				continue; 
			}
			if($name == 'users') {
				$fieldLabels[$key] = $this->_('Users'); // Label for 'users' field
				continue;
			}
			$field = wire('fields')->get($name);
			$languageID = wire('user')->language ? wire('user')->language->id : '';
			$label = $field->get('label' . $languageID);
			if(!$label) $label = $field->label; 
			if(!$label) $label = $name; 
			$fieldLabels[$key] = htmlentities($label, ENT_QUOTES, "UTF-8");
		}

		$table->headerRow($fieldLabels); 
		$selector = "limit=25, status<" . Page::statusMax; 
		$pages = $this->page->children($selector); 

		foreach($pages as $page) {
			if(!$page->editable()) continue; 
			$n = 0; 
			$row = array();
			foreach($fieldNames as $name) {
				if($name == "users") {
					$row[] = count($page->children);
				} else {
					if(!$n) $row[(string)$page->get($name)] = "edit/?id={$page->id}";
						else $row[] = $this->renderListFieldValue($name, $page->get($name)); 
				}
				$n++;
			}
			$table->row($row); 
		}

		if($pages->getTotal() > count($pages)) {
			$pager = $this->modules->get("MarkupPagerNav"); 
			$out .= $pager->render($pages);
		}

		$out .= $table->render();

		return $out; 
	}

	/**
 	 * Modify the output per-field in the PageType list (template-method)
	 *
	 * In this case we make it return a count for the language_files
	 *
	 */
	protected function renderListFieldValue($name, $value) {
		if($name == 'users') {
			return count($this->page->get()->children); 
		} else if($name == 'title') { 
			if(!$value) return '(blank)';
			return (string) $value;
		} else {
			return parent::renderListFieldValue($name, $value); 
		}
	}
	
	public function ___install() {
		// $this->___uninstall();
		//parent::___install();
		$configData = array();
		
		/**
		 * Create login template
		 */
		// create sociallogin_process field
		$field = new Field();
        $field->type = $this->modules->get('FieldtypeModule');
		$field->name = 'sociallogin_process';
		$field->label = 'Login Process';
		$field->description = 'Stores the login process';
		$field->flags = Field::flagSystem;
		$field->save();
		
		// create the fieldgroup to be used by the login template
		$fieldgroup = new Fieldgroup(); 
		$fieldgroup->name = 'sociallogin';
		$fieldgroup->add($this->fields->get('title')); 
		$fieldgroup->add($field); // sociallogin_process
		$fieldgroup->save();		
		
		// create template
		$template = new Template();	
		$template->name = 'sociallogin';
		$template->fieldgroup = $fieldgroup;  
		$template->slashUrls = 1; 
		$template->pageLabelField = 'name';
		$template->nameContentTab = 1; 
		$template->flags = Template::flagSystem;
        $template->allowUrlSegments = 1; 
		$template->save();
		$this->message("Created Template: sociallogin");
		
		// create page
		$login = new Page($template);
		$login->parent = $this->fuel('pages')->get("/");
		$login->name = "login";
		$login->title = "Social Login";
		$login->process = $this->modules->get('ProcessSocialLogin'); // INSTALL ProcessSocialLogin
		$this->message("Installed ProcessSocialLogin"); 
		$login->save();
		$this->message("Created Page: ".$login->path);

		/**
		 * Create manager page in backend
		 */
		$adminPage = $this->fuel('pages')->get($this->config->adminRootPageID); 
		$setupPage = $adminPage->child("name=setup"); 
		if(!$setupPage->id) throw new WireException("Unable to locate {$adminPage->path}setup/"); 

		// create the manager parent page
		$manager = new Page();
		$manager->parent = $setupPage; 
		$manager->template = $this->templates->get('admin'); 
		$manager->process = $this->modules->get('ProcessSocialLoginManager'); 
		$manager->name = 'sociallogin';
		$manager->title = 'Social Login Providers';
		$manager->status = Page::statusSystem; 
		$manager->sort = $setupPage->numChildren; 
		$manager->save();

		$configData['socialloginPageID'] = $manager->id;
        
        /**
         * Create user template
         */ 
        // create template
        $template = new Template(); 
        $template->name = 'sociallogin_user';
                
        // create the fieldgroup to be used by the user template
        $fieldgroup = new Fieldgroup(); 
        $fieldgroup->name = $template->name;
        $fieldgroup->add($this->fields->get('title')); 

        // create sociallogin_user field
        $field = new Field();
        $field->type = $modules->get('FieldtypePage');
        $field->name = $template->name;
        $field->label = 'Social Login: User Page Reference';
        $field->flags = Field::flagSystem;
        $field->template_id = $templates->get('user')->id;
        $field->derefAdPage = 1; 
        $field->save();
        $fieldgroup->add($field);         
        $this->message("Created field: sociallogin_user");
        
        // create sociallogin_user_data field
        $field = new Field();
        $field->type = $this->modules->get('FieldtypeTextarea');
        $field->name = 'sociallogin_user_data';
        $field->label = 'Social Login: User data';
        $field->description = 'Stores the login process';
        $field->flags = Field::flagSystem;
        $field->save();        
        $fieldgroup->add($field);
        $this->message("Created field: sociallogin_user_data");
        
        $fieldgroup->save();
        
        $template->fieldgroup = $fieldgroup;  
        $template->slashUrls = 1; 
        $template->pageLabelField = 'name';
        $template->nameContentTab = 1; 
        $template->flags = Template::flagSystem;
        $template->allowUrlSegments = 1; 
        $template->save();
        $this->message("Created Template: sociallogin_user");
        
		$this->message("Social Login Installed! Click to the 'Setup' menu to manage Social Login Providers.");
		$default = $this->modules->get('ProcessSocialLoginProviderDefault');

	}
	
	public function ___uninstall() {
		/**
		 * Remove manager page in backend
		 */
		$adminPage = $this->fuel('pages')->get($this->config->adminRootPageID); 
		$manager = $adminPage->child("name=setup")->child('name=sociallogin'); 
		if($manager->id) { //throw new WireException("Unable to locate {$adminPage->path}setup/sociallogin/");
            $manager->status = Page::statusSystemOverride;
            $manager->status = 0;
            $manager->save();
    		$this->pages->delete($manager, true); 				
        }
		$this->modules->uninstall($this->modules->get('ProcessSocialLogin'));
        $login = $this->pages->get('template=sociallogin');
        if($login->id) {
            $login->status = Page::statusSystemOverride;
            $login->status = 0;
            $login->save();
            $this->pages->delete($login);
        }
		$template = $this->templates->get('sociallogin');
        if($template->id) {
    		$template->flags = Template::flagSystemOverride;
            $template->flags = 0;
    		$template->save();
            $temp_name = $template->name;
    		$this->templates->delete($template);
            $this->fieldgroups->delete($this->fieldgroups->get($temp_name));
        }
        
        $field = $this->fields->get('sociallogin_process');
        if($field->name) {
            $field->flags = Field::flagSystemOverride;
            $field->flags = 0;
            $field->save();
	        $this->fields->delete($field);
        }
        
        $template = $this->templates->get('sociallogin_user');
        if($template->id) {
            $template->flags = Template::flagSystemOverride;
            $template->flags = 0;
            $template->save();
            $temp_name = $template->name;
            $this->templates->delete($template);
            $this->fieldgroups->delete($this->fieldgroups->get($temp_name));
        }
        
        $fields = array(
            $this->fields->get('sociallogin_user'),
            $this->fields->get('sociallogin_user_data')
            );
        foreach($fields as $field) {
            if($field->name) {
                $field->flags = Field::flagSystemOverride;
                $field->flags = 0;
                $field->save();
                $this->fields->delete($field);
            }
        }        
		
		return parent::___uninstall();
	}

}
?>